version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11.11-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./_volume/data/:/var/lib/rabbitmq/
      # - ./_volume/log/:/var/log/rabbitmq
  app:
    image: image-builder:latest
    network_mode: host
    env_file:
      - ./config/.env
    deploy:
      mode: replicated
      replicas: 3