[phases.setup]
nixPkgs = ["...","nixpacks","golangci-lint"]

[phases.lint]
dependsOn = ["install"]
cmds = ["go fmt .","golangci-lint run"]

[phases.build]
dependsOn = ["...","lint"]

[phases.test]
dependsOn = ["...","build"]
cmds = ["go test -v ./..."]