app:
  name: "image-builder"
  version: "0.0.1"

rabbitmq:
  uri: amqp://guest:guest@localhost:5672/
  exchangeQueue: test

logger:
  level: "debug"
  type: "text"

database:
  driver: "mock"

services:
  downloaders:
    - name: github
      downloadDirectory: "./tmp"
  builders:
    - name: nixpacks
      registryUri: "registry.example.com"
