app:
  name: "image-builder"
  version: "0.0.1"

rabbitmq:
  exchangeQueue: test

logger:
  level: "debug"
  type: "text"

database:
  driver: "mock"

services:
  downloaders:
    - name: github
      downloadDirectory: "./tmp"
  builders:
    - name: nixpacks
  registries:
    - name: docker
      serverAddress: "localhost:5000"
